// <auto-generated />
using CalculatorWebApi.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculatorWebApi.Migrations
{
    [DbContext(typeof(ArdhamaticDbContext))]
    partial class ArdhamaticDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CalculatorWebApi.model.Entity.Arthamatic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("oprand1")
                        .HasColumnType("double");

                    b.Property<double>("oprand2")
                        .HasColumnType("double");

                    b.Property<double>("result")
                        .HasColumnType("double");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Arthamatic");
                });
#pragma warning restore 612, 618
        }
    }
}
